<a href="https://colab.research.google.com/github/benjapalomino/Datascience/blob/main/MAT4141_Formulario_ET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Formulario Python para MAT4141**

compresion lectora


alzar = total

condicion = incoloro y exclente = index

In [ ]:
df = pd.read_excel('ET_Base.xlsx')

5 pregunta

In [ ]:
precio = df["Precio (dólares)"]

el30 = precio.quantile(0.70)
el30

np.float64(4535.0)

In [ ]:
alto = df['Alto (mm)']

media = alto.mode()
media

0    4.41
Name: Alto (mm), dtype: float64

In [ ]:
df.tail(1)

,Peso (quilates),Precio (dólares),Corte,Color,Claridad,Ancho (mm),Alto (mm),Profundidad (mm),Porcentaje de profundidad
400,1.51,7455,Premium,Amarillo pálido,Excelente,7.38,7.29,4.62,63.0

83

1,42 y los 1,72 quilates

30

1,72 y los 2,02 quilates.

6

### Importar bibliotecas o librerías

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import skew, kurtosis, norm

### Generar un DataFrame de nombre **df** a partir de un archivo (Excel o CSV) con base de datos subida al entorno en Colab

In [ ]:
#Nombre del DataFrame, por ejemplo, df

#Base de datos en formato xlsx (excel)
df = pd.read_excel('nombre del archivo que contiene la base de datos.xlsx')

#Base de datos en formato csv
df = pd.read_csv('nombre del archivo que contiene la base de datos.csv')

### Mostrar las n primeras filas de un DataFrame de nombre **df**

In [ ]:
#Muestra las primeras n filas del DataFrame
df.head(n)

### Cantidad de filas de un DataFrame de nombre **df**

In [ ]:
#Número de filas
filas = df.shape[0]

### El conjunto de valores distintos observados para una **variable** de un DataFrame de nombre **df**

In [ ]:
df['Nombre de la variable'].unique()

### Tabla de frecuencia para variable **cualitativa** de un DataFrame de nombre **df**

In [ ]:
#Cálculo de frecuencia absoluta. La palabra frecuencia representa la frecuencia absoluta.
frecuencia = df.groupby('Nombre de la variable').size()

n = df.shape[0]

#Crear el DF con frecuencias absolutas y relativas
tabla = pd.DataFrame({
    'fi': frecuencia,
    'hi': round((frecuencia/n) *100, 1) # redondear según contexto y valores de los datos.
})
tabla

### Tabla de frecuencia para variable **cuantitativa continua** de un DataFrame de nombre **df**

In [ ]:
#Agregar una columna al DataFrame df

k = cantidad de intervalos #Debe ingresar este valor
n = tamaño de la muestra #Debe ingresar este valor
d = cantidad de decimales de los intervalos #Debe ingresar este valor

df['Intervalos'] = pd.cut(df['Nombre de la variable'], bins = k, include_lowest= True, precision = d)
frecuencia = df.groupby('Intervalos', observed = True).size()

tabla_continua = pd.DataFrame({
    'fi': frecuencia,
    'hi': (frecuencia/n)*100,
    'Fi':frecuencia.cumsum(),
    'Hi': ((frecuencia/n) * 100).cumsum()

})
tabla_continua #Puede indicar redondear con m cantidad de decimales round(tabla_continua,m)

### Gráfico para variable de un DataFrame de nombre **df**

In [ ]:
#Gráfico circular

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida
categorias = tabla.index  #Indices de la tabla
h = tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig,ax = plt.subplots(figsize = (6,4)) #Tamaño de la figura
circular = ax.pie(h, labels = categorias, autopct= '%.1f%%')

#Personalización
ax.set_title('Título del gráfico')

plt.show()

In [ ]:
#Gráfico de barras

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida

#Variables
categorias = tabla.index
f = tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig, ax = plt.subplots(figsize = (6,6))
barras = ax.bar(categorias, f, color = 'r', edgecolor ='black') #Los colores son de libre elección

#Personalización
ax.set_title('Título del gráfico')
ax.set_xlabel('Título eje x')
ax.set_ylabel('Título eje y')
ax.bar_label(barras)
plt.xticks(rotation=45) #Rota en 45° las categorías para evitar la superposición
plt.show()

In [ ]:
#Histograma

#Considerar que "tabla" es el nombre de la tabla de frecuencias construida

#Variables
categorias = tabla.index
f= tabla['Frecuencia']   #Considerar que "Frecuencia" es el tipo de frecuencia a graficar

#Gráfico
fig, ax = plt.subplots(figsize = (7,5))
histograma= ax.bar(categorias.astype(str), f, color = 'r', edgecolor = 'black', width = 1) #Los colores son de libre elección

#Personalización
ax.set_title('Título del gráfico')
ax.set_xlabel('Título eje x')
ax.set_ylabel('Título eje y')
ax.bar_label(histograma, fmt = '%.1f%%') #El argumento fmt controla la cantidad de decimales a mostrar
plt.xticks(rotation=45, ha = 'right') #Rota en 45° las categorías para evitar la superposición
plt.show()

### Medidas de posición y dispersión para una variable cuantitativa de un DataFrame de nombre **df**

In [ ]:
media = df['Nombre de la variable'].mean()

mediana = df['Nombre de la variable'].median()

moda = df['Nombre de la variable'].mode()

percentil_k = df['Nombre de la variable'].quantile(k) #ingrese el valor "k" en decimal

desviacion_estandar = df['Nombre de la variable'].std()

### Cálculo de medidas de asociación para el DataFrame **df**

In [ ]:
#Covarianza
covarianza = df['Variable independiente'].cov(df['Variable dependiente'])

#Coeficiente de correlación lineal de Pearson
coef_correlacion = df['Variable independiente'].corr(df['Variable dependiente'])

### Modelo de regresión lineal usando los datos del DataFrame **df**

In [ ]:
#Defición de variables independiente y dependiente
v_indep = df['Nombre de la variable independiente']
v_depen = df['Nombre de la variable dependiente']

modelo_lineal = np.polyfit(v_indep,v_depen,1)
pendiente, intercepto = modelo_lineal

### Coeficiente de determinación $R^{2}$ de un modelo de regresión lineal

In [ ]:
#Calcular predicciones según el modelo de regresión lineal obtenido
predicciones_v_depen = np.polyval(modelo_lineal, v_indep)

#Cálculo del coeficiente de determinación R2
R2 = r2_score(v_depen, predicciones_v_depen)

### Gráfico de dispersión

In [ ]:
#Defición de variables independiente y dependiente
v_indep = df['Nombre de la variable independiente']
v_depen = df['Nombre de la variable dependiente']

#Crear gráfico de dispersión
fig,ax = plt.subplots(figsize = (6,5))
dispersion = ax.scatter(v_indep, v_depen)

#Línea de tendencia
ax.plot(v_indep, pendiente * v_indep + intercepto, color='red', label= f'y={pendiente:.2f}x+{intercepto:.2f}')

#Personalización
ax.set_title('Título del gráfico')
ax.set_xlabel('Título eje x (unidades)')
ax.set_ylabel('Título eje y (unidades)')

ax.legend()
plt.show()

### Cálculo de probabilidades usando los datos del DataFrame **df**

In [ ]:
# Frecuencia absoluta (dos variables)
Tabla_frec_abs = pd.crosstab(df['Variable 1'], df['Variable 2'],margins= True)


# Probabilidad simple (% del total)
probabilidad_simple = df['Nombre de la variable'].value_counts(True) * 100


# Probabilidad conjunta o condicional
probabilidad = pd.crosstab(df['Variable 1'], df['Variable 2'], normalize= 'TIPO', margins= True) * 100
# Cambiar el parámetro normalize según el TIPO de cálculo:
# 'all' → probabilidad total
# 'index' → probabilidad condicional por filas
# 'columns' → probabilidad condicional por columnas

### Coeficiente de asimetría y Curtosis de una variable del DataFrame **df**

In [ ]:
#Coeficiente de asimetría
asimetria=skew(df['Nombre de la variable'])

#Curtosis
curtosis=kurtosis(df['Nombre de la variable'])

### Cálculo de probabilidades de una variable que sigue una distribución normal del DataFrame **df**

In [ ]:
#Probabilidad menor que b
prob_menor_b = norm.cdf(b, media, desviacion_estandar)*100